### ISSUE TITLE
Issues with Processing Images with different labels.

### ISSUE THREAD

**Issue by hitesha14** [ysbecca/py-wsi#17]
##Patches with Different Labels do not get Processed Correctly.

I have tried to process images with different labels. The image patches that are generated belong to single default label of type 0. I have tried customizing the code but to no avail.  Also I have tried running the program at various levels from Level 1 to Level 16 that is the maximum number of levels which exist for the image I am processing. However I get image patches or tiles with only default label 0. 

Please could you suggest what can be done so that all the patches belonging to different labels are extracted correctly rather just going into the default Normal or Label 0. I have tried my level best to resolve it, however I wasn't able to extract image patches with valid labels correctly.

@ysbecca Please could let me know I am stuck up in the middle of my research.

**Comment by hitesha14** [comment]
Hi Rebecca,

 I am extremely thankful to you for your amazing work. I am attaching a sample of my xml annotation file for the above mentioned issue. Please go through it and suggest accordingly. This is a part of my research work.

Awaiting your reply.   
![annotationxml](https://user-images.githubusercontent.com/8632760/51518336-87b5ee00-1e43-11e9-925d-4d172c470919.PNG)

**Comment by ysbecca** [comment]
Hi @hitesha14, I would suggest debugging this in the following way:

Copy the function `get_regions(path)` in the file `patch_reader.py` into a separate Python file or Jupyter notebook. This function takes an absolute path to an XML annotation file. 

Find out exactly what this function is returning when you give it your XML. It returns a tuple of `regions` and `region_labels`. 

`region_labels` should **exactly match** what you have specified in your label dictionary. In my Jupyter notebook example, I call it `label_map` in cell [2]. 

You can get an error either because your `label_map` dict is NOT matching what is in `region_labels` so it's returning the default label, OR because your XML is not in the expected format (although it looks ok to me from your image above) and the regions and/or labels are not read correctly.

**Comment by ysbecca** [comment]
Instead of using the Shapely module (poly, Point, etc) to check whether a point is in a region, you could instead use the annotations to generate binary PNG images, with a unique integer for each region and a separate unique integer for background. Then you can label your patches by comparing with the binary mask.

I would suggest generating at least a few of these binary masks regardless to double check that your annotations are valid, if you say it is reading in correctly.
