### ISSUE TITLE
'storage_type' error still, after update the version of py-wsi 

### ISSUE THREAD

**Issue by dl-miao** [ysbecca/py-wsi#24]
Hi, @ysbecca  
Firstly, thanks a lot for your work!

I am a new to py_wsi, I met a problem when create the turtle object. Once I add the storage_type option, it will has the following error. I've read the previous issue, so I upgrade the the version of py-wsi, it still has the same problem!

----> 1 turtle = py_wsi.Turtle(file_dir, db_location, db_name, xml_dir=xml_dir, label_map=label_map, storage_type='lmdb')

TypeError: __init__() got an unexpected keyword argument 'storage_type'

**Comment by ysbecca** [comment]
Hmm... when you check the py-wsi code, in the file turtle.py (where the Turtle class is defined), do you see the storage_type parameter present?

**Comment by dl-miao** [comment]
hi @ysbecca 
Thanks for your so quickly response! and sorry for my late reply.  I've fix the error!

**Comment by nazim1021** [comment]
Hi @ysbecca  @dl-miao , I am facing a similar error. I also checked the turtle.py file and storage_type parameter is present. Any idea on how do I fix this error ?
I have updated version of py-wsi and my python version is 3.7

**Comment by ysbecca** [comment]
Hmm, have you installed an older version using pip? Maybe when you import
py_wsi you are importing the old version somehow.... I suggest adding a
print statement inside the turtle file to confirm that you really are
importing the correct version.

**Comment by nazim1021** [comment]
Thanks so much for the response. Yes, it was the version issue, I had installed py_wsi through pip which had an older version. Later, I directly cloned the git repo and imported py_wsi through that and It worked well :)

**Comment by ysbecca** [comment]
Great! Glad you've got it sorted.

**Comment by natachalevy** [comment]
Hi @ysbecca, I am experiencing the same issue! I cloned the git repo, I checked in the turtle file if the storage_type parameter was present and it is! But the same error keeps coming up. Do you have any other suggestions on how I could fix this error? Thanks a lot! :)

**Comment by ysbecca** [comment]
Hmm, you're sure you've completely uninstalled any old versions? If it's importing in the right files, it will see the storage_type param. Maybe stick a print statement inside the new version, to double check you're importing what you hope you are.

**Comment by natachalevy** [comment]
Hi rebecca! Thanks for your fast response! I indeed still had an older version (downloaded with pip install) in my site packages so I uninstalled that. I reinstalled the package through cloning the git repo however now it doesn’t seem to find it anymore and gives me the ‘No module named ‘py_wsi’ ’. As you may tell I am not an experienced programmer and therefore I am having some trouble troubleshooting. I followed this tutorial to fork and clone the repo https://docs.github.com/en/github/getting-started-with-github/fork-a-repo.
I am not sure how to deal with this issue now, do you think it might be because the py_wsi is in the folder py-wsi and my computer (mac) is having trouble finding it?

Thank you again for your help 😊

Natacha

**Comment by ysbecca** [comment]
HI Natacha,
You'll need to tell Python where the module you want to load is; ie, the
simplest is if you are in a Python file at the same level as the py_wsi
folder. Then a direct "import py_wsi" should work. If you aren't in that
directory then you will need to tell Python where to find it.

Rebecca
