### ISSUE TITLE
Doubts about py_wsi xml file

### ISSUE THREAD

**Issue by luistelmocosta** [ysbecca/py-wsi#4]
Hello, I know that this is not the best place to ask, but I got some doubts. 
My project dissertation is Deep Learning for oncocytic cells detection and I'm using py_wsi to load images. However, I don't understand how I can use the .xml file to label my patches. 
You have:

```
label_map = {'Normal': 0,
             'Benign': 1,
             'Carcinoma in situ': 2,
             'In situ carcinoma': 2,
             'Carcinoma invasive': 3,
             'Invasive carcinoma': 3,
            }
```

- Are those labels discriminated on the xml file? 

Also, I think that cropping the image without a _preprocessing_ can jeopardize some of the cell information since you may be slicing a cell in half. 

I really think this part should be treated carefully because it will have serious repercussions in the segmentation phase and every feature I can extract is crucial.

Thank you in advance, your usage example is guiding me in these first steps and I really appreciate it. 

Regards

**Comment by ysbecca** [comment]
Hello, 

Most annotations on whole slide images are done using ImageScope (Aperio) or similar software, which is why py_wsi is built to read that specific format. In the `label map`, the String keys of the dictionary correspond to the labels the pathologist gave to the regions in the XML annotation. If you're not sure what your labels are, you can open the XML file and check; in this example, `Text="Benign"`, so that is the String key you should set for the label map. 

![image](https://user-images.githubusercontent.com/2350526/42973250-737aa844-8baa-11e8-8724-8f15044030eb.png)

About the cropping, it doesn't matter because typically patches are sampled with significant overlap; for every feature, there will at least be one patch in which that feature is completely present. You should choose a patch size large enough such that this is true. 

To get the final output for an image you will need to aggregate all your predictions from each patch. Some papers (but there are many!) using this kind of patch sampling with stride:

- [An Automatic Learning-Based Framework for Robust Nucleus Segmentation](https://ieeexplore.ieee.org/abstract/document/7274740/)
- [A Dataset and a Technique for Generalized Nuclear Segmentation for Computational Pathology](https://www.dropbox.com/s/j3154xgkkpkri9w/IEEE_TMI_NuceliSegmentation.pdf?dl=0)

Also, I suggest you **fork the py_wsi repository** when using it in your project; that way you can see what is happening and make any personal tweaks you may like.

Hope this is a little helpful! Best wishes with your project.

**Comment by luistelmocosta** [comment]
Thank you so much for your reply!

Yes, I'm familiar with XML files. But I don't have any Region tag on my xml file. I was just wondering if it is a disease specific or I downloaded the wrong xml.

Just a final question, I'm tiling my image with the _deepest_ **level**. But after the processing I get a database with 51 gb which is impossible to load. Is there any way to load just a few or any other workaround?

Sorry for bothering you. I'm just trying to get into it asap

Kind Regards

**Comment by ysbecca** [comment]
It's possible that your XML file is formatted differently - the format is determined the software used for annotations and the type of annotation. In that case, I would suggest forking and downloading py_wsi and customising the function which reads the XML file.

And yes, the DBs do get quite large! You will want to load the data in sets. See the Jupyter notebook example under section "Loading patches from LMDBs" for several options about how to load only parts of the dataset at a time.

**Comment by luistelmocosta** [comment]
I swear I read that Notebook over three times and I did not see that topic until just now, I'm sorry.
Thank you so much for your replies. You're great!

**Comment by luistelmocosta** [comment]
After reading the section "Loading patches from LMDBs" - point 2, I got confused. 
You say that the "ith image in the directory belongs to the ith set". What happens when you only have one image and you want to load just a set of patches?
I set my `set_id` to 0 (since I have one single image) but it still looks computationally infeasible to load an image at higher levels. The process always ends with a SIGKILL signal.

**Comment by ysbecca** [comment]
Sorry for the delayed response, somehow I missed this! As you noted, `set_id` is meant for a dataset of more than one image. It should be feasible though to load a single image into memory! I don't recommend doing it inside a Jupyter Notebook.
