### ISSUE TITLE
Bad install on macOs Big Sur and python 3.9.0

### ISSUE THREAD

**Issue by Octopus-inc** [ysbecca/py-wsi#40]
Hi there!
Im using python 3.9.0 and working in virtualenv. 
I just following for your instruction:

```
- brew install openslide
- pip install py_wsi
```

and here is my `pip list` output after that:
```
Package          Version
---------------- -------
h5py             3.1.0
lmdb             1.0.0
numpy            1.19.4
openslide-python 1.1.2
Pillow           8.0.1
pip              20.3.1
py-wsi           1.1
setuptools       49.2.1
Shapely          1.7.1
wheel            0.36.1
```
I see the same errors:
```
ModuleNotFoundError: No module named 'py_wsi'
ModuleNotFoundError: No module named 'openslide'
```
Plz help!

**Comment by ysbecca** [comment]
Hi @Octopus-inc, this doesn't fix your specific problem, but as mentioned in the README, I strongly recommend cloning or forking the repo instead of using pip to install py_wsi. The pip version is very outdated - sorry, I should just remove it, to prevent confusion!

In general, though, it looks as if the packages are installed. When you try to import, are you sure you are in the same virtualenv? Try:

```bash
(name_of_your_venv) $ python
Python 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
>>> import openslide
>>>
```

**Comment by Octopus-inc** [comment]
**SOLVED**

Your advice showed that libraries can be imported, but **do not work in a Jupiter Notebook** that is not installed in venv (as we see in the `pip list` output in my previous post) but exist in global. After installing Jupiter in venv by using pip, everything began to work.

I guess this is not a problem of the library - a problem of the virtual environment and me. You can delete this release if you like.
Thank you very much.
